version: "3.5"
services:
  motioneye:
    restart: unless-stopped
    # The 'image' directive is inherited from the base docker-compose.yml
    # To build from local source, ensure 'build: .' is uncommented in the base file.
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
    volumes:
      - /etc/localtime:/etc/localtime:ro
